project:
  type: website

website:
  title: "Python Pour Les Nuls"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: var_ope.qmd
        text: Variables et Opérations
      - href: comm_affiche.qmd
        text: Commentaires et Affichage
      - href: struct_controle.qmd
        text: Structures de contrôle
      - href: types_donnees.qmd
        text: Types de données
      - about.qmd


format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



