project:
  type: website

website:
  title: "Python, Quésaco ? 🐍"
  navbar:
    left:
      - href: index.qmd
        text: Acceuil
      - href: var_ope.qmd
        text: Variables et Opérations
      - href: comm_affiche.qmd
        text: Commentaires
      - href: struct_controle.qmd
        text: Structures de contrôle
      - href: types_donnees.qmd
        text: Types de données
      - href: fonctions.qmd
        text: Fonctions
      - href: exercices.qmd
        text: Exercices
      - about.qmd


format:
  html:
    theme: zephyr
    css: styles.css
    toc: true



